menu:
#- {name: 'people', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'Teaching', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

#people:
#- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
#- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
  - semester: "Spring 2026"
    school: "Rice"
    code: "STAT 410"
    title: "Linear Regression"
    url: ""

  - semester: "Fall 2025"
    school: "Rice"
    code: "STAT 425"
    title: "Introduction to Bayesian Inference"
    url: "Rice-STAT-425"

  - semester: "Spring 2025"
    school: "Duke"
    code: "STA 611"
    title: "Introduction to Mathematical Statistics (<span style='color:#c0392b; font-style:italic;'>Head TA</span>)"
    url: '' #"Duke-STA-611"

  - semester: "Fall 2024"
    school: "Duke"
    code: "STA 521"
    title: "Predictive Inference (<span style='color:#c0392b; font-style:italic;'>Head TA</span>)"
    url: '' #"Duke-STA-521"

social:
- {icon: 'github', link: 'https://jkstatai.github.io/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/justin-kao-asa-9248ba16a/'}

contacts:
- {name: 'Justin Kao', title: 'PhD Student', department: 'Statistics', institution: 'Rice University', email: 'Justin.Kao@rice.edu', address: '(Maxfield Hall) 6100 Main St MS 364, Houston, TX 77005', image: 'assets/img/contact.jpeg'}
