menu:
#- {name: 'people', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'Teaching', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

#people:
#- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
#- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
  - semester: "Fall 2025"
    code: "STAT 425"
    title: "Intro to Bayesian"
    url: "Rice-STAT-425"

  - semester: "Spring 2025"
    code: "STA 611"
    title: "Introduction to Mathematical Statistics"
    url: "Duke-STA-611"

  - semester: "Fall 2024"
    code: "STA 521"
    title: "Predictive Inference"
    url: "Duke-STA-521"

social:
- {icon: 'github', link: 'https://jkstatai.github.io/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/justin-kao-asa-9248ba16a/'}

contacts:
- {name: 'Justin Kao', title: 'PhD Student', department: 'Statistics', institution: 'Rice University', email: 'Justin.Kao@rice.edu', image: 'assets/img/contact.jpeg'}
